source/accounts/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import RegisterView, UserDetailView, UsersList, UserChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('accounts/login', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('create/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='user_detail' ),
    path('users/', UsersList.as_view(), name='users_list' ),
    path('change/' , UserChangeView.as_view(), name='user_change'),
    path('password_change/', UserPasswordChangeView.as_view(), name='password_change')
]

source/tracker/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views import IndexView, DoingView, DoingUpdateView, DoingDeleteView, ProjectView, ProjectDetailView, \
    DoingCreateView, ProjectCreateView, ProjectUpdateView, ProjectDeleteView, ChangeUserInProject

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('doings/<int:pk>/', DoingView.as_view(), name='doing_view'),
    path('doing/<int:pk>/update/', DoingUpdateView.as_view(), name='doing_update'),
    path('doing/<int:pk>/delete/', DoingDeleteView.as_view(), name='doing_delete'),
    path('projects/', ProjectView.as_view(), name='projects_list'),
    path('project/<int:pk>/', ProjectDetailView.as_view(), name='project_view'),
    path('project/<int:pk>/doing/add', DoingCreateView.as_view(), name='project_doings_add'),
    path('project/create', ProjectCreateView.as_view(), name='project_create'),
    path('project/<int:pk>/update', ProjectUpdateView.as_view(), name='project_update'),
    path('project/<int:pk>/delete', ProjectDeleteView.as_view(), name='project_delete'),
    path('project/<int:pk>/add_users', ChangeUserInProject.as_view(), name='add_users'),

]

source/webapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.
class Status(models.Model):
    statusname = models.CharField(max_length=150, null=False, blank=False, verbose_name="Статус")

    def __str__(self):
        return f'{self.statusname}'

class Type(models.Model):
    typename = models.CharField(max_length=150, null=False, blank=False, verbose_name="Тип")

    def __str__(self):
        return f'{self.typename}'

class Doings(models.Model):
    summary = models.CharField(max_length=200, null= False, blank= False, verbose_name="Краткое описание")
    description = models.TextField(max_length=2000, null= True, blank=True, verbose_name="Описание")
    status = models.ForeignKey('webapp.Status', related_name='status', on_delete=models.PROTECT, verbose_name="Статус")
    type = models.ManyToManyField('webapp.Type', related_name='type', blank=True)
    create = models.DateTimeField(auto_now_add=True, verbose_name='Создание')
    update = models.DateTimeField(auto_now=True, verbose_name='Обновление')
    task = models.ForeignKey('webapp.Projects', related_name="doings",on_delete=models.CASCADE, verbose_name="Задача")
    def __str__(self):
        return f'{self.pk}. {self.summary}'


class Projects(models.Model):
    start_date =models.DateField(null=False,blank=False, verbose_name="Начало")
    end_date =models.DateField(null= True, blank=True, verbose_name="Конец")
    name = models.CharField(max_length=30, null=False,blank=False, verbose_name="Название")
    description = models.TextField(max_length=400,null=False,blank=False, verbose_name="Описание")
    users = models.ManyToManyField(get_user_model(), related_name='projects')

    class Meta:
        permissions = [
            ('can_add_users', "может добавлять участников"),
            ('can_delete_users', "может удалять участников")
        ]
    def __str__(self):
        return f'{self.name}'

source/webapp/forms.py
from django import forms
from webapp.models import Status, Type , Doings
from django.forms import widgets , ValidationError

from webapp.models import Projects


class DoingForm(forms.ModelForm):
    class Meta:
        model = Doings
        fields = ['summary', 'description', 'status', 'type']
        widgets = {'description':widgets.Textarea, 'type':widgets.CheckboxSelectMultiple}

    def clean_summary(self):
        summary = self.cleaned_data['summary']
        if len(summary) < 3:
            self.add_error('summary', ValidationError('*Введите больше 3 символов'))
        return summary

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data['summary'] == cleaned_data['description']:
            raise ValidationError('Описание не должно совпадать с названием')
        return cleaned_data



class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label="Найти")

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Projects
        fields = ['name', 'description', 'start_date', 'end_date']
        widgets = {'start_date':widgets.SelectDateWidget, 'end_date':widgets.SelectDateWidget}

class UserInProjectForm(forms.ModelForm):
    class Meta:
        model = Projects
        fields = ['users']
        widgets = {'users': widgets.CheckboxSelectMultiple}

source/webapp/views/doings_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import get_object_or_404
from webapp.models import Doings , Status , Type , Projects
from webapp.forms import DoingForm , SimpleSearchForm
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.db.models import Q
from django.utils.http import urlencode


class IndexView(ListView):
    template_name = 'doings/index.html'
    context_object_name = 'doings'
    model = Doings
    ordering = ['-create']
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
         context['query'] = urlencode({'search': self.search_value})
         context['search'] = self.search_value
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)
        
    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None

class DoingView(DetailView):
    template_name = 'doings/doings_view.html'
    model = Doings

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        doings = self.object
        context['doings'] = doings
        return context
class DoingCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'doings/doings_create.html'
    model = Doings
    form_class = DoingForm
    permission_required = 'webapp.add_doings'

    def has_permission(self):
        return super().has_permission() or Projects.users == self.request.user


    def form_valid(self, form):
        task = get_object_or_404(Projects, pk=self.kwargs.get('pk'))
        form.instance.task = task
        return super().form_valid(form)


    def get_success_url(self):
        return reverse('webapp:doing_view', kwargs={'pk': self.object.pk})

class DoingUpdateView(PermissionRequiredMixin, UpdateView):
    model = Doings
    template_name = 'doings/update.html'
    form_class = DoingForm
    context_object_name = 'doing'
    permission_required = 'webapp.change_doings'

    def has_permission(self):
        return super().has_permission() or Projects.users == self.request.user

    def get_success_url(self):
        return reverse('webapp:doing_view', kwargs={'pk': self.object.pk})

class DoingDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'doings/delete.html'
    model = Doings
    context_object_name = 'doing'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_doings'

    def has_permission(self):
        return super().has_permission() or Projects.users == self.request.user

source/webapp/views/projects_views.py
from django.contrib.auth.mixins import  PermissionRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from webapp.models import Projects
from webapp.forms import ProjectForm , UserInProjectForm


class ProjectView(ListView):
    template_name = 'projects/project_list.html'
    context_object_name = 'projects'
    model = Projects

class ProjectDetailView(DetailView):
    template_name = 'projects/project_detailview.html'
    model = Projects

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        projects = self.object
        doings = projects.doings.order_by('-create')
        context['doings'] = doings
        return context



class ProjectCreateView(PermissionRequiredMixin , CreateView):
    template_name = 'projects/project_create.html'
    model = Projects
    form_class = ProjectForm
    permission_required = 'webapp.add_projects'

    def form_valid(self, form):
        self.object = form.save()
        self.object.users.add(self.request.user)
        return super().form_valid(form)

    def has_permission(self):
        return super().has_permission()

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.pk})

class ProjectUpdateView(PermissionRequiredMixin , UpdateView):
    model = Projects
    template_name = 'projects/project_update.html'
    form_class = ProjectForm
    context_object_name = 'projects'
    permission_required = 'webapp.change_projects'

    def has_permission(self):
        return super().has_permission()

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.pk})

class ProjectDeleteView(PermissionRequiredMixin,DeleteView):
    template_name = 'projects/project_delete.html'
    model = Projects
    context_object_name = 'projects'
    success_url = reverse_lazy('webapp:projects_list')
    permission_required = 'webapp.delete_projects'

    def has_permission(self):
        return super().has_permission()

class ChangeUserInProject(PermissionRequiredMixin,UpdateView):
    template_name = 'projects/add_users_in_project.html'
    model = Projects
    form_class = UserInProjectForm
    context_object_name = 'project'
    permission_required = 'webapp.can_add_users'

    def has_permission(self):
        project = get_object_or_404(Projects, pk=self.kwargs.get('pk'))
        return super().has_permission() and self.request.user in project.users.all()

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.pk})

source/webapp/templates/projects/add_users_in_project.html
{% extends "base.html" %}
{% block title %}Add users in Project{% endblock %}
{% block content %}
 <form action="" method="post">
        {% include "partial/form.html" with button_text="Add" %}
    </form>



{% endblock %}

source/webapp/templates/projects/delete_users_project.html
{% extends "base.html" %}
{% block title %}Delete users in Project{% endblock %}
{% block content %}
 <form action="" method="post">
        {% include "partial/form.html" with button_text="Delete" %}
    </form>



{% endblock %}

source/webapp/templates/projects/project_create.html
{% extends 'base.html' %}
{% block content %}


<body>
    <form action="" method="post">
        {% include "partial/form.html" with button_text="Create" %}

    </form>

</body>

{% endblock %}

source/webapp/templates/projects/project_delete.html
{% extends "base.html" %}

{% block title %}Delete Issue{% endblock %}
{% block nav %}
{% endblock %}
{% block content %}
    <h1 class="text-center mt-5">Are you sure want to delete project "{{ projects.name }}"?</h1>
    <form method="POST" action="{% url "webapp:project_delete" projects.pk %}" class="text-center">
        {% csrf_token %}
        <p class="mt-5"><input type="submit" value="Confirm" class="btn btn-dark"></p>
        <p><a class="btn btn-secondary" href="{% url "webapp:project_view" projects.pk %}">Cancel</a></p>
    </form>

{% endblock %}

source/webapp/templates/projects/project_detailview.html
{% extends 'base.html' %}
{%  block nav %}
    {% if request.user.is_authenticated %}
        {% for users in projects.users.all %}
            {% if perms.webapp.add_doings and  users == request.user %}
                <li class="nav-item">
                      <a class="nav-link" href="{% url 'webapp:project_doings_add' projects.pk %}">Task Add+</a>
                </li>
            {% endif %}
        {% endfor %}
    {% if perms.webapp.change_projects %}
        <li class="nav-item">
              <a class="nav-link" href="{% url 'webapp:project_update' projects.pk %}">Update Project</a>
        </li>
    {% endif %}
    {% if perms.webapp.delete_projects %}
        <li class="nav-item">
              <a class="nav-link" href="{% url 'webapp:project_delete' projects.pk %}">Delete Project</a>
        </li>
    {% endif %}
    {% endif %}
    {% for users in projects.users.all %}
        {% if perms.webapp.can_add_users and  users == request.user %}
            <li class="nav-item">
                  <a class="nav-link" href="{% url 'webapp:add_users' projects.pk %}">Change Users</a>
            </li>
        {% endif %}
    {% endfor %}

{%  endblock %}
{% block content %}

<h3>Project: {{ projects.name }}</h3>
    <h5>Description: {{ projects.description }}</h5>
    <p>Start: {{ projects.start_date }}</p>
    <p>End: {{ projects.end_date }}</p>
    <p>Users in Project: {% for users in projects.users.all %}<a style="color:black;" href="{%  url 'accounts:user_detail' users.pk %}">{{ users }}</a>{% if not forloop.last %} , {% endif %}{% endfor %}</p><hr/>
{% for doing in doings %}
    <h4>{{ doing.summary }}</h4>
    <p>{{ doing.description }}</p>
    <p>{{ doing.status }}</p>
    <p><a class="btn btn-dark" href="{% url 'webapp:doing_view' doing.pk %}">More...</a></p>
    {% if request.user.is_authenticated %}
        {% for users in projects.users.all %}
            {% if perms.webapp.change_doings and users == request.user %}
                <a class="btn btn-dark"  href="{% url 'webapp:doing_update' doing.pk %}">Edit</a>
            {% endif %}
            {% if perms.webapp.delete_doings and  users == request.user %}
                <a class="btn btn-dark" href="{% url 'webapp:doing_delete' doing.pk %}">Delete</a>
            {% endif %}
        {% endfor %}

    {% endif %}
    <hr>

{% endfor %}<br/>


{%  endblock %}

source/webapp/templates/projects/project_list.html
{% extends 'base.html' %}
{%  block nav %}
    {% if request.user.is_authenticated %}
        {% if perms.webapp.add_projects %}
            <li class="nav-item">
                  <a class="nav-link" href="{% url 'webapp:project_create' %}">Create new Project+</a>
            </li>
        {% endif %}
    {% endif %}
{%  endblock %}
{% block content %}

{% include 'partial/projects_list_partial.html' %}
{%  endblock %}

source/webapp/templates/projects/project_update.html
{% extends "base.html" %}

{% block title %}Update Project{% endblock %}
{% block content %}
    <h1>Update Project</h1>

    <form action="" method="post">
        {% include "partial/form.html" with button_text="Update" %}
    </form>
{% endblock %}